server:
  port: 8088
  context-path: /ysynzehao
  
spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
    format_sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-test?autoReconnect=true&autoReconnectForPools=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: admin
    password: admin